//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGTPPE2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKETS()
        {
            this.Localiser = new HashSet<Localiser>();
        }
    
        public int idTicket { get; set; }
        public string emplacementMaterielTicket { get; set; }
        public string typeMaterielTicket { get; set; }
        public string descriptionIncident { get; set; }
        public System.DateTime dateCreationIncident { get; set; }
        public System.DateTime dateClotureIncident { get; set; }
        public int idUtilisateur { get; set; }
        public int idUrgence { get; set; }
        public string numeroSerieMateriel { get; set; }
        public int etatStatut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Localiser> Localiser { get; set; }
        public virtual MATERIEL MATERIEL { get; set; }
        public virtual NIVEAUURGENCETICKET NIVEAUURGENCETICKET { get; set; }
        public virtual STATUT STATUT { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
